### ISSUE TITLE
收藏模式不能使用了？

### ISSUE THREAD

**Issue by xiozf** [genzj/pybingwallpaper#21]
wiki里关于收藏模式的说明不见了，很贴心的功能，为何取消了呢？

**Comment by genzj** [comment]
wiki已经更新 [收集每日必应壁纸](https://github.com/genzj/pybingwallpaper/wiki/%E6%94%B6%E9%9B%86%E6%AF%8F%E6%97%A5%E5%BF%85%E5%BA%94%E5%A3%81%E7%BA%B8)
