### ISSUE TITLE
Configuration of selecting the country is not working.

### ISSUE THREAD

**Issue by kingFighter** [genzj/pybingwallpaper#28]
version: 1.4.4
os: win7
Whether I edit the *settings.conf* or use *cli* to change the country, the wall paper is always the same(俯瞰北京长安街 9/10).

By the way, I wonder how you find the wall paper download address
(/HPImageArchive.aspx?format=js&mbl=1&idx=0&n=1&cc=us). 

Through *ImgViewer* function?

**Comment by genzj** [comment]
Sorry for late response, very busy with personal affairs recently. 

- What's the configuration key and country code you changed to? You can try set `market = en-gb`. However I find out bing.com redirects all China mainland IP requests to its China site. No idea why...
- You can check the `_parse` method of class `BingWallpaperPage` in `bingwallpaper.py`. Just a series of JSON parsing and consulting works.

**Comment by genzj** [comment]
close this issue due to lacking of debug materials. please feel free to reopen if necessary.
