### ISSUE TITLE
自启动项和安装路径问题

### ISSUE THREAD

**Issue by huangpiaoyi** [genzj/pybingwallpaper#31]
自启动快捷方式似乎有一个参数-b，也就是说即使settings.conf设置了Background = False，该程序仍然会因为自启动项的设置而强制在后台运行了，请问能否修改默认设置，改成不带参数的？
另外，win7开始对program file文件夹的权限限制变得比较死，所以默认安装在那里就会导致修改setting.conf比较麻烦，非要在开始菜单右键选择以管理员身份运行才行。建议可以修改默认设置，改为在%appdata%\Genzj\PyBingWallpaper下安装~

**Comment by genzj** [comment]
`1. 自启动快捷方式应该支持无驻留` 已加入1.5.0开发
