### ISSUE TITLE
希望卸载时仅删除安装程序释放的目录与文件

### ISSUE THREAD

**Issue by xiozf** [genzj/pybingwallpaper#33]
我将图片的保存位置设置在pybingwallpaper的安装目录内，起了个名字叫wallpaper。上次升级到1.44时使用自带的卸载程序卸载，发现卸载程序直接删掉pybingwallpaper这个安装目录，连带我自己建立的文件夹和图片文件一并删了。
希望卸载检测更严格一些。

**Comment by genzj** [comment]
卸载时默认只会卸载安装程序自带的文件和目录。但是有的用户有无残留卸载的需求，所以有一个提示，询问是否删除配置文件，实质上是删除了整个安装目录，包括用户自己创建的内容。

我还是保留了以上行为，但是对提示做了更改，提示用户会删除所有文件，特别指出如果下载的图片在其中也会被删除。
