### ISSUE TITLE
Extend "collect" parameter to all markets

### ISSUE THREAD

**Issue by zulrak1** [genzj/pybingwallpaper#35]
Hi

Another request for genzj when he is available for this application.

Sometimes there are Chinese Bing logos for markets other than EN-WW (ROW filenames) like this FR-FR pair:

http://www.bing.com/az/hprichbg/rb/CribFiguresMarseille_FR-FR11175577358_1920x1200.jpg
http://www.bing.com/az/hprichbg/rb/CribFiguresMarseille_FR-FR11175577358_ZH_1920x1200.jpg

The extension of "collect" for other markets should also be done for ZH-CN. For ex. the following wallpaper does not exist in standard nomenclature, without "_ZH_":

http://www.bing.com/az/hprichbg/rb/BerlinWall_ZH-CN13913064474_ZH_1920x1200.jpg

tks

zulrak

**Comment by genzj** [comment]
I'm adding this to code. Do you know if bing logo got other languages besides default English and Chinese? I tried JP/JR/JA but no fortune.

**Comment by zulrak1** [comment]
I've also tried other languages with their own characters but only ZH-CN
has a specific logo. That can be seen in each market homepage:

http://www.bing.com/?mkt=zh-cn   (the logo is Chinese)

Remaining markets have a standard logo, even ZH-HK (Hong Kong) and ZH-TW
(Taiwan).

List of possible markets or regions, (now and then changing) can be seen in
Bing homepage settings page:

http://www.bing.com/account/ (REGION section)

Interestingly since around one week ago ZH-CN with regular nomenclature
began showing a standard logo, not a Chinese logo as used to be. But now
there a version suffixed by "_ZH_" having Chinese logo.

Example:

http://www.bing.com/az/hprichbg/rb/GemsbokFight_ZH-CN10139164269_1920x1200.jpg
           (std logo)


http://www.bing.com/az/hprichbg/rb/GemsbokFight_ZH-CN10139164269_ZH_1920x1200.jpg
      (Chinese logo)

EN-WW (ROW) continue to have two versions of logos. Now and then other
markets do the same.
