### ISSUE TITLE
这个app的Windows版是用什么工具打包的？

### ISSUE THREAD

**Issue by redstoneleo** [genzj/pybingwallpaper#36]
我也在学习Python，看到你这个app我想问下是用什么工具打包的？

**Comment by genzj** [comment]
从py源文件到exe用的[cx_Freeze](http://cx-freeze.sourceforge.net/)；Windows安装包用[NSIS](http://nsis.sourceforge.net/Main_Page).

**Comment by redstoneleo** [comment]
多谢了
