### ISSUE TITLE
可以更新一下么，windows8.1好像有点问题

### ISSUE THREAD

**Issue by githubsystem** [genzj/pybingwallpaper#37]
不知道作者还更不更新了，希望添加个界面

**Comment by genzj** [comment]
界面不一定会加，因为和软件的功能定位有关系，你可以试试bing best，功能类似，界面很漂亮。http://www.iplaysoft.com/bing-best.html

另外请问Windows 8有什么问题呢？我的电脑太老跑不了Windows 8，麻烦你描述下问题和复现过程，我请朋友弄一下。谢谢了！

**Comment by genzj** [comment]
暂无回复，先关闭这个issue，如果有更新请reopen。
