### ISSUE TITLE
WinError 183

### ISSUE THREAD

**Issue by Ices-Eyes** [genzj/pybingwallpaper#40]
Hi.
For some time now, it happen this error eevry time i launch pybingwallpaper executable. I have already tried to change directory, or removing contents, but after some time the problem appears again. Any advice?

Thanks!
![error](https://cloud.githubusercontent.com/assets/13162428/11612689/8e5f6c32-9c04-11e5-82aa-0cbd6b2b5fe2.png)

**Comment by genzj** [comment]
sorry for the inconvenience. which version are you using?

**Comment by Ices-Eyes** [comment]
Hi. Nothing to be sorry for ;)
The version is the latest available, 1.4.4. It has benn working for months, then now it started with this problem. Possibily some sort of incompatibility with windows 10?

**Comment by genzj** [comment]
not sure if it particularly happens to win10, but I'm sure in win 7 the mode is 555 and never changes. seems current the file is marked as mode 777. anyhow, let me fix it and release a new version by tomorrow night. Thank you for letting me know about that:)

**Comment by Ices-Eyes** [comment]
Thanks man! Will look forward for the new version ;)

**Comment by genzj** [comment]
Rev 1.5.0 has been released. Please feel free to download and try it. Thank you for your supporting! :+1: :smile:

**Comment by Ices-Eyes** [comment]
Thanks to you! Now it works correctly ;)
