### ISSUE TITLE
how to close the "bing" logo in wallpaper?

### ISSUE THREAD

**Issue by jiazhaoyang** [genzj/pybingwallpaper#42]
how to close the "bing" logo in wallpaper?

**Comment by genzj** [comment]
bing embedded the logo into all its wallpaper pictures. Is using lower resolution picture an acceptable solution? If so, you can add `--image-size=1920x1080 --size-mode=manual` arguments to command line, or change corresponding options in configuration file. Feel free to change `1920x1080` to the desirable resolution. You may need to try several times till find the correct one fitting your screen among what bing.com offers.

Thanks for paying attention to this project!

**Comment by jiazhaoyang** [comment]
可以用中文吗？我对程序不熟，不知道怎么在命令行增加那些参数。右下角的logo难道不是你的程序自己加的吗？其他的壁纸程序都没有logo，不过总是开机需要关联元权限启动。谢谢了

**Comment by genzj** [comment]
1. logo不是程序加的，是微软做的。我没有找到无logo的原始大图地址，其他程序可能是下载低分辨率的图片，就是我之前说的方式；

2. 你打开程序的安装路径，里面有个`settings.conf`文件，默认路径是`C:\Users\jmzhu\AppData\Roaming\<你的用户名>\PyBingWallpaper\settings.conf`，用记事本打开这个文件，找到`size_mode = highest`改成`size_mode = manual`，还有`image_size = `改成`image_size = 1920x1080`

**Comment by jiazhaoyang** [comment]
好的，谢谢了。你打算做可视化的界面吗？我是交互设计师，可以简单帮忙设计一下。

**Comment by genzj** [comment]
呵呵，谢谢你！暂时不准备做了，工作比较忙，这个项目都很少维护，而且我主要在Linux下使用，再加入图形界面也违背初衷。不过如果你有做开发的朋友愿意做图形化的版本，可以直接fork我的代码，这是MIT开源的，我也很乐意贡献一些开发工作。

谢谢！
