### ISSUE TITLE
版本1.5.0下载之后windows defender提示病毒

### ISSUE THREAD

**Issue by leim** [genzj/pybingwallpaper#44]
无论是从百度盘还是dropbox下载的安装包，都提示有病毒，win10x64系统，windows defender。

![111](https://cloud.githubusercontent.com/assets/1665397/14129626/3ba36354-f65e-11e5-9904-97a44dd9ec3f.PNG)

![222](https://cloud.githubusercontent.com/assets/1665397/14129628/42ddb44e-f65e-11e5-809d-3995887fa0d0.PNG)

**Comment by genzj** [comment]
请提供一下windows defender病毒库的版本，应该在defender管理控制窗口的更新页面。谢谢！

**Comment by leim** [comment]
这里
![333](https://cloud.githubusercontent.com/assets/1665397/14130071/a0660b26-f662-11e5-9afc-fba90d010599.PNG)

**Comment by genzj** [comment]
没找到怎么给微软提误报，等我重新打个包试试吧。

**Comment by genzj** [comment]
不知你是否有空帮我测试下这个版本：

> http://pan.baidu.com/s/1pK7GVDT
> 提取码usq3

如果还是不行我就考虑换打包工具了。
谢谢！

**Comment by leim** [comment]
已下载，windows defender未报告异常。

**Comment by genzj** [comment]
好的，非常感谢！

**Comment by gecece** [comment]
@genzj  现在用的是什么打包工具呢，我想自己打包~

**Comment by gecece** [comment]
代码是用python3写的啊……

我用cx_freeze遇到了问题，比如 `ImportError: No module named 'win32.win32gui'`，安装了pywin32还是不行，还有PIL怎么在python3下使用？

有时间能不能简单写个Wiki，说明一下配置和发布的过程，万分感谢~

**Comment by genzj** [comment]
pywin32装完应该就好了，PIL装一个叫pillow的库。
