### ISSUE TITLE
为什么设置的壁纸是带水印的？

### ISSUE THREAD

**Issue by cxyfreedom** [genzj/pybingwallpaper#45]
我看了一下bingwallpaper.py里面的路径，我把url单独拉出来试一下应该是无水印的，为什么系统设置完的wallpaper是带水印的？谢谢

**Comment by genzj** [comment]
请把你实验用的url给我一下，谢谢～

**Comment by cxyfreedom** [comment]
@genzj http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1可以获取到

**Comment by genzj** [comment]
json里面的地址类似 `http://s.cn.bing.net/az/hprichbg/rb/CoffeeSprouts_ROW13568224527_1920x1080.jpg` 不带水印，但是默认取了1920x1200的分辨率（如果存在），`http://s.cn.bing.net/az/hprichbg/rb/CoffeeSprouts_ROW13568224527_1920x1200.jpg`做壁纸，而这个高分辨率的是有水印的。

要是不需要1920x1200那么高分辨率的话，可以编辑一下设置文件，把`size_mode`设为`manual`，把`size_mode`设为`1920x1080`就可以了。

```
image_size = 1920x1080
size_mode = manual
```

**Comment by cxyfreedom** [comment]
原来如此，谢谢解答
