### ISSUE TITLE
卸载之后不能换桌面[Unable to use customize settings in Win10 after uninstallaion]

### ISSUE THREAD

**Issue by ion2014** [genzj/pybingwallpaper#49]
使用之后只有该软件可以更改桌面, 别的程序都不能换, 卸载后重启也没用, 右键桌面个性化设置被禁用, 提示: 某些设置由你的组织管理. 请问作者改了什么设置..怎么调回来?

**Comment by genzj** [comment]
软件没做过相关的锁定，无论卸载与否，都是可以手动修改桌面图片的。
看提示信息怀疑是组策略问题，请参考[这个](https://answers.microsoft.com/zh-hans/windows/forum/windows_10-start/win10/f83ed265-1d46-4bd4-99f4-a7fd79178405) 或类似的页面排查下。谢谢！
