### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by Computer-Science-Student** [genzj/pybingwallpaper#53]
请问获得的必应壁纸上的水印有办法去除吗？其他的感觉都挺好了，就这一点差强人意...

**Comment by AHBICJ** [comment]
https://github.com/genzj/pybingwallpaper/issues/45
可以查看已经关闭的issues

**Comment by genzj** [comment]
多谢 @AHBICJ 
如#45，只能下载没有水印的版本了，

**Comment by Computer-Science-Student** [comment]
谢谢二位的解答！
