### ISSUE TITLE
The program crashed strangely

### ISSUE THREAD

**Issue by slanterns** [genzj/pybingwallpaper#54]
```
[2019-03-10 08:28:02,483 - INFO - main] download photo of "皇家高地燧发枪团在悉尼歌剧院屋顶演奏风笛 (\xa9 James D Morgan/Shutterstock)"
Traceback (most recent call last):
  File "C:\Users\jmzhu\Envs\pybingwallpaper\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "./src/main.py", line 704, in <module>
  File "./src/main.py", line 558, in main
  File "./src/main.py", line 452, in download_wallpaper
  File "./src/main.py", line 485, in save_a_picture
OSError: [Errno 22] Invalid argument: 'C:\\Users\\nic\\MyBingWallpapers\\th?id=OHR.BagpipeOpera_ZH-CN9506207351_1920x1080.jpg'
```

**Comment by gwy15** [comment]
Windows does not support character '?' in filenames. You can try escaping the filename before creating files.

**Comment by genzj** [comment]
Bing changed the downloading url to include filename as url parameter. I will update the filename extraction to adapt.

**Comment by slanterns** [comment]
>Bing changed the downloading url to include filename as url parameter. I will update the filename extraction to adapt.

thanks.

**Comment by genzj** [comment]
fix in 1aca4f

please feel free to have a try.

thanks a lot for the problem reporting 😸

**Comment by slanterns** [comment]
Could you please release a packed executable version?

**Comment by genzj** [comment]
sure. I uploaded the RC to dropbox. If everything goes well I will release it on github.

[download pybingwp-1-5-4.exe](https://www.dropbox.com/s/7ikopbgme8ms889/pybingwp-1-5-4.exe?dl=0)

```
https://www.dropbox.com/s/7ikopbgme8ms889/pybingwp-1-5-4.exe?dl=0

CRC32: 73597245
MD5: 32E90C3AB472C1D063AECA545E8F3006
SHA-1: 6F998AB9BCFAF9269D8C251031B4C6CF60811FCE
SHA-256: A67F3AD20AB33BEE3E76BD1C72040D052C89C5A7F8031A0A90F1DEB0D95EAE97
```

**Comment by slanterns** [comment]
It works well. Thanks!
