### ISSUE TITLE
在settings.conf下修改background = True是否就可以不用在启动文件里添加-b命令？

### ISSUE THREAD

**Issue by hrflni** [genzj/pybingwallpaper#57]
[Download]
redownload = False
customserver = 
offset = 0
market = 
keep_file_name = True
server = global
size_mode = highest
image_size = 
output_folder = E:\MyBingWallpapers
country = auto
collect = hdvideo,accompany

[Proxy]
proxy_server = 
proxy_password = 
proxy_username = 
proxy_port = 80

**[Daemon]
interval = 1
background = True**

[Setter]
setter_args = 
setter = win

[Database]
database_file = 
database_no_image = False

[Debug]
debug = 0

**Comment by genzj** [comment]
是的，没错，两者等价。

**Comment by hrflni** [comment]
> 
> 
> 是的，没错，两者等价。

我试了一下，如果是在启动快捷方式，程序还是会自动关闭。
需要在软件目录下运行才可以直接读取settings.conf，常驻后台。

**Comment by genzj** [comment]
这是因为在开始菜单快捷方式里加上了`foreground`的参数，需要的话可以编辑一下快捷方式删了这个参数就好
![Snipaste_2019-05-23_13-34-06](https://user-images.githubusercontent.com/1018413/58227976-a1b6fd00-7d5f-11e9-9fe0-591ed5a6530d.png)

**Comment by hrflni** [comment]
> 
> 
> 这是因为在开始菜单快捷方式里加上了`foreground`的参数，需要的话可以编辑一下快捷方式删了这个参数就好
> ![Snipaste_2019-05-23_13-34-06](https://user-images.githubusercontent.com/1018413/58227976-a1b6fd00-7d5f-11e9-9fe0-591ed5a6530d.png)

我是安装好后直接在 .exe 后面删除了 -b ，我这里启动项后面只有这个参数。
我再看看。
