### ISSUE TITLE
为什么会有修改输入法的提示？

### ISSUE THREAD

**Issue by JerryLees** [genzj/pybingwallpaper#58]
![image](https://user-images.githubusercontent.com/6364966/58524561-30fa5f80-81fb-11e9-996e-cdb60bb2bda7.png)

**Comment by genzj** [comment]
没发现过这个问题，先看看安装文件检验码吧，我装个QQ拼音看看。

> CRC32: 87327ADF
> MD5: 28445D14062FC174B807F4D8BD9511FF 
> SHA-1: 5E99D0F3004630CFA5043FEB1265868562563A53
> SHA-256: D81F93F57917115CD730D2BEC051BC2E07532A910B44EFBAEB6AD81A40C452E9
