### ISSUE TITLE
最近时常无法自动更换壁纸

### ISSUE THREAD

**Issue by free4537** [genzj/pybingwallpaper#60]
如题。

**Comment by genzj** [comment]
多谢反馈，我查一下。谢谢！

**Comment by genzj** [comment]
你好，

我换了几个环境，也试了不同的接口，都可以正常更换。应该不是Bing接口修改。

麻烦你运行开始菜单里面的`PyBingWallpaper Commandline Mode`，然后把输出的信息复制给我，我看看还有什么问题。

谢谢！

**Comment by free4537** [comment]
找到原因了，是我本地代理服务器配置导致的。不好意思，打扰了。
