### ISSUE TITLE
为什么我设置了US地区，程序还是下载中国地区的壁纸，我是中国的用户

### ISSUE THREAD

**Issue by guoyucheng97** [genzj/pybingwallpaper#61]
country 和 market都设置为us，可是还是下载中国地区的wallpaper，可以解决吗？
[2020-03-18 22:57:40,381 - INFO - bingwallpaper.main] running config is:
        background = True
        collect = []
        config_file = 'c:\\users\\administrator\\appdata\\roaming\\genzj\\pybing
wallpaper\\settings.conf'
        country = 'us'
        customserver = ''
        database_file = ''
        database_no_image = False
        debug = 0
        foreground = True
        generate_config = False
        image_size = ''
        interval = 2
        keep_file_name = False
        list_markets = False
        market = 'en-us'
        offset = 0
        output_folder = 'C:\\Users\\Administrator\\MyBingWallpapers'
        proxy_password = ''
        proxy_port = '80'
        proxy_server = ''
        proxy_username = ''
        redownload = True
        server = 'global'
        setter = 'win'
        setter_args = []
        size_mode = 'prefer'
[2020-03-18 22:57:40,381 - INFO - bingwallpaper.main] running config is:
        background = True
        collect = []
        config_file = 'c:\\users\\administrator\\appdata\\roaming\\genzj\\pybing
wallpaper\\settings.conf'
        country = 'us'
        customserver = ''
        database_file = ''
        database_no_image = False
        debug = 0
        foreground = True
        generate_config = False
        image_size = ''
        interval = 2
        keep_file_name = False
        list_markets = False
        market = 'en-us'
        offset = 0
        output_folder = 'C:\\Users\\Administrator\\MyBingWallpapers'
        proxy_password = ''
        proxy_port = '80'
        proxy_server = ''
        proxy_username = ''
        redownload = True
        server = 'global'
        setter = 'win'
        setter_args = []
        size_mode = 'prefer'
[2020-03-18 22:57:40,401 - INFO - bingwallpaper.bingwallpaper] loading from http
://www.bing.com/HPImageArchive.aspx?format=js&mbl=1&idx=0&n=1&video=1&mkt=en-us
[2020-03-18 22:57:40,501 - INFO - bingwallpaper.bingwallpaper] 890 bytes loaded
[2020-03-18 22:57:40,501 - WARNING - bingwallpaper.bingwallpaper] links to be do
wnloaded: [(('http://www.bing.com/th?id=OHR.KeichitsuCrocuse_ZH-CN1061292366_192
0x1200.jpg',), {'copyright': '藏红花 (© Hayami Yanagisawa/Getty Images)', 'copyr
ightlink': 'https://www.bing.com/search?q=%E8%97%8F%E7%BA%A2%E8%8A%B1&form=hpcap
t&mkt=zh-cn', 'hsh': '3817f0577050774c325d404a9da97981', 'market': 'zh-CN', 'sta
rtdate': datetime.date(2020, 3, 17), 'enddate': datetime.date(2020, 3, 18), 'ful
lstartdate': datetime.datetime(2020, 3, 17, 16, 0)})]
[2020-03-18 22:57:40,511 - INFO - bingwallpaper.main] file has been downloaded b
efore, redownload it
[2020-03-18 22:57:40,511 - INFO - bingwallpaper.main] download photo of "藏红花
(© Hayami Yanagisawa/Getty Images)"
[2020-03-18 22:57:40,581 - INFO - bingwallpaper.main] file saved C:\Users\Admini
strator\MyBingWallpapers\wallpaper.jpg
[2020-03-18 22:57:40,581 - INFO - bingwallpaper.main] setting wallpaper C:\Users
\Administrator\MyBingWallpapers\wallpaper.jpg
[2020-03-18 22:57:40,731 - INFO - bingwallpaper.main] all done. enjoy your new w
allpaper
[2020-03-18 22:57:40,731 - INFO - bingwallpaper.main] force foreground mode from
 command line

**Comment by genzj** [comment]
bing服务器检测到访问IP是中国大陆IP时始终会跳转到大陆的服务器，无论配置了哪个市场或者国家。目前没发现什么好的解决办法。如果有翻墙代理的话，可以配置一下proxy选项，走代理就行了。

**Comment by guoyucheng97** [comment]
谢谢解答
