### ISSUE TITLE
可以升级一下支持UHD壁纸吗

### ISSUE THREAD

**Issue by Gimhoy** [genzj/pybingwallpaper#63]
现在可以下载4K壁纸了

**Comment by genzj** [comment]
好的，我研究下，多谢！

**Comment by genzj** [comment]
@Gimhoy 请问有4k壁纸的链接么？我在bing主页看了几个还是1920x1200或者1920x1080的

**Comment by Gimhoy** [comment]
> @Gimhoy 请问有4k壁纸的链接么？我在bing主页看了几个还是1920x1200或者1920x1080的

https://www.bing.com/th?id=OHR.ParnidisSundial_ZH-CN9575177836_UHD.jpg

把1920x1080改成UHD就行了

**Comment by genzj** [comment]
https://github.com/genzj/pybingwallpaper/releases/tag/REV_1_6_0

好了，可否麻烦你帮我试试？谢谢！

**Comment by Gimhoy** [comment]
很好用，谢谢~太高效了~！
