### ISSUE TITLE
setting中如何设置从国内版bing下载壁纸？

### ISSUE THREAD

**Issue by babikiu** [genzj/pybingwallpaper#64]
现在的设置应该默认从国际版下载了壁纸，我想选择从国内版下载，是在[Download]的country处更换为China吗？还是在server更换？
[Download]
**country = auto**
market = 
keep_file_name = False
size_mode = prefer
collect = 
image_size = 
offset = 0
redownload = False
output_folder = C:\Users\vcbea\MyBingWallpapers
**server = global**
customserver =

**Comment by genzj** [comment]
你好，设置`country = cn`就可以了，注意是cn而不是china。
如果还是不行，可以设置`country = auto`和`market = zh-cn`。country是比较早期的接口，market出现得晚一些且支持更多国家地区，但是对于修改到国内版，两者效果一样。

`server = china`时会使用国内必应站点`s.cn.bing.net`，但是没有隐含任何country和market的设置，所以大部分情况下，只修改server，没有任何可见的效果。

**Comment by babikiu** [comment]
谢谢回复
